# Generated by Django 5.1.2 on 2024-12-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_imagem_uploaded_at_alter_imagem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='posts_images/'),
        ),
    ]
