# Generated by Django 5.1.2 on 2024-12-12 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_imagem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Imagem',
        ),
    ]
