# Generated by Django 5.1.2 on 2024-10-15 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='about',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
