# Generated by Django 5.1.2 on 2024-10-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='perfilPhoto',
            field=models.ImageField(blank=True, upload_to='perfilPhoto'),
        ),
    ]
