# Generated by Django 5.1.2 on 2024-10-19 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_usuario_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='perfilPhoto',
            field=models.ImageField(blank=True, default='perfilPhoto/perfil-default.jpg', null=True, upload_to='perfilPhoto'),
        ),
    ]
