# Generated by Django 5.1.2 on 2024-11-02 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_remove_usuario_perfilphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='perfilPhoto',
            field=models.ImageField(blank=True, default='perfilPhoto/perfil-default.jpg', null=True, upload_to='perfilPhoto'),
        ),
    ]
