# Generated by Django 5.1.2 on 2024-11-02 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_usuario_perfilphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='perfilPhoto',
        ),
    ]
